import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/app/Navbar";
import { ToastContainer } from "react-toastify";
import { UserProvider } from "./UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} bg-gray-800 max-w-[1200px] mx-auto`}
      >
        <UserProvider>
          <Navbar />
          {children}
          <ToastContainer />
        </UserProvider>
      </body>
    </html>
  );
}
